### ISSUE TITLE
Why count(*) > 50 ?

### ISSUE THREAD

**Issue by uditagarwal97** [TestRoots/travistorrent-tools#6]
>     select u.login, p.name, p.language, count(*)
>     from projects p, users u, watchers w
>     where
>         p.forked_from is null and
>         p.deleted is false and
>         w.repo_id = p.id and
>         u.id = p.owner_id
>     group by p.id
>     having count(*) > 50
>     order by count(*) desc
In the query you have used to fetch data from GHTorrent, what's the use of having count(*) > 50?

**Comment by Inventitech** [comment]
> According to GHTORRENT, GITHUB hosted 17,313,330
active OSS repositories (including forks) in August, 2015.
However, many of these 17 million projects are toy projects
or duplicated (forks with no or tiny modifications). In our
analysis, we are interested in state-of-the-art software systems
that have a larger real-world user base. To retrieve a meaningful
sample of projects from GITHUB, we follow established
project selection instructions [44]: we selected all projects that
are not forks themselves, and received more than 50 stars

Source: https://inventitech.com/publications/2017_beller_gousios_zaidman_oops_my_tests_broke_the_build_an_explorative_analysis_of_travis_ci_with_github.pdf

**Comment by uditagarwal97** [comment]
OK.. thanks
